import type { DraftTransaction, Transaction } from "./types";

export const storageKeys = {
  transactions: "finance-dashboard-transactions",
  role: "finance-dashboard-role",
  theme: "finance-dashboard-theme",
};

export const openingBalance = 14250;

export const sampleTransactions: Transaction[] = [
  {
    id: "txn-001",
    date: "2026-03-28",
    title: "Salary Credit",
    amount: 92000,
    category: "Salary",
    type: "income",
    account: "Primary Account",
    note: "Monthly payroll",
  },
  {
    id: "txn-002",
    date: "2026-03-27",
    title: "Apartment Rent",
    amount: 28000,
    category: "Housing",
    type: "expense",
    account: "Primary Account",
  },
  {
    id: "txn-003",
    date: "2026-03-26",
    title: "Index Fund SIP",
    amount: 15000,
    category: "Investments",
    type: "expense",
    account: "Wealth Account",
  },
  {
    id: "txn-004",
    date: "2026-03-24",
    title: "Freelance Invoice",
    amount: 18500,
    category: "Side Hustle",
    type: "income",
    account: "Primary Account",
  },
  {
    id: "txn-005",
    date: "2026-03-21",
    title: "Supermarket Run",
    amount: 4680,
    category: "Groceries",
    type: "expense",
    account: "Card",
  },
  {
    id: "txn-006",
    date: "2026-03-19",
    title: "Dining Out",
    amount: 2360,
    category: "Food",
    type: "expense",
    account: "Card",
  },
  {
    id: "txn-007",
    date: "2026-03-14",
    title: "Health Insurance",
    amount: 5400,
    category: "Insurance",
    type: "expense",
    account: "Primary Account",
  },
  {
    id: "txn-008",
    date: "2026-03-09",
    title: "App Subscription Refund",
    amount: 1499,
    category: "Refunds",
    type: "income",
    account: "Card",
  },
  {
    id: "txn-009",
    date: "2026-02-28",
    title: "Salary Credit",
    amount: 92000,
    category: "Salary",
    type: "income",
    account: "Primary Account",
  },
  {
    id: "txn-010",
    date: "2026-02-25",
    title: "Flight Booking",
    amount: 11800,
    category: "Travel",
    type: "expense",
    account: "Card",
  },
  {
    id: "txn-011",
    date: "2026-02-19",
    title: "Electricity Bill",
    amount: 3150,
    category: "Utilities",
    type: "expense",
    account: "Primary Account",
  },
  {
    id: "txn-012",
    date: "2026-02-12",
    title: "Bonus Payout",
    amount: 22000,
    category: "Bonus",
    type: "income",
    account: "Primary Account",
  },
];

export const createEmptyDraft = (): DraftTransaction => ({
  date: new Date().toISOString().slice(0, 10),
  title: "",
  amount: 0,
  category: "Groceries",
  type: "expense",
  account: "Primary Account",
  note: "",
});
